namespace WebApp.Models.Enums;

public enum TSql
{
    CADASTRAR_LIVRO,
    LISTAR_LIVROS,
    PESQUISAR_LIVRO,
    EXCLUIR_LIVRO,
    ATUALIZAR_LIVRO,
    
    CADASTRAR_CLIENTE,
    LISTAR_CLIENTES,
    PESQUISAR_CLIENTE,
    EXCLUIR_CLIENTE,
    ATUALIZAR_CLIENTE
}