namespace WebApp.Models.Enums;

public enum TSql
{
    CADASTRAR_LIVRO,
    LISTAR_LIVROS,
    PESQUISAR_LIVRO,
    EXCLUIR_LIVRO,
    ATUALIZAR_LIVRO,
    
    EMPRESTAR_LIVRO,
    LISTAR_LIVROS_EMPRESTADOS,
    PESQUISAR_EMPRESTIMO,
    ATUALIZAR_EMPRESTIMO,
    
    CADASTRAR_CLIENTE,
    LISTAR_CLIENTES,
    PESQUISAR_CLIENTE,
    EXCLUIR_CLIENTE,
    ATUALIZAR_CLIENTE,
    
    CADASTRAR_USUARIO,
    LISTAR_USUARIOS,
    PESQUISAR_USUARIO,
    EXCLUIR_USUARIO,
    ATUALIZAR_USUARIO,
    EFETUAR_LOGIN,
}